### ISSUE TITLE
sdk/state: don't allow unauthorized states to be discarded

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#103]
We need to make sure to preserve any unauthorized close agreement that we haven't received signatures from the other participant. This is necessary to ensure the participants can close a channel in any event that a participant falls behind confirming and but submits a declaration without sharing signatures for the close with the other participant. This problem is highlighted by the changes we've made to use CAP-40 (#176), but existed before it as well.

This probably means making the `lastUnauthorizedCloseAgreement` a list of agreements, where whenever agreement in the list gets updated it moves itself to `lastAuthorizedCloseAgreement` and discards any agreements that proceed it.

A simpler solution to this would be to say that only one unauthorized agreement can exist at a time, which is essentially what we have now, although it is unenforced, and to enforce that.

I think we should do the simpler solution until we find a need for supporting multiple in flight at once. I think the protocol should be able to support multiple, which it does, but the SDK doesn't need to initially.

**Comment by acharb** [comment]
if I understand this correctly the edge case is:
```
A proposes {ca1}
B confirms {ca1}, but doesn't send sigs back to A
A proposes {ca2}, B submits ca1, and A can't finish ca1 because second proposal cleared its partially finished {ca1}
```
the simpler solution of enforcing that A cannot propose {ca2} until {ca1} is finished makes sense to me (at the expense of TPS I think), but I'm wondering shouldn't A be able to get what it needs from the {ca1} that B broadcasted to the network?
