### ISSUE TITLE
sdk/state: store the observation period on close agreements and use for decisioning

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#106]
Now that we've made the change to make the main thing we store is close agreements (#102) we have no way of distinguishing between close agreements that require waiting the observation period with close agreements that were coordinated and have no observation period.

This code stores a coordinated close, but there's nothing being stored that signals it is coordinated and there is no delay required in following up with the close transaction.
https://github.com/stellar/experimental-payment-channels/blob/5f62767b82e79b784591f8a0a17408772ca094d5/sdk/state/close.go#L57-L61

**Comment by leighmcculloch** [comment]
@acharb you originally stored the observation period on a type, this is probably the right time to reintroduce that as that would be more functional than simply adding an 'isCoordinated' to the agreement.

**Comment by acharb** [comment]
> you originally stored the observation period on a type, this is probably the right time to reintroduce that

sgtm for adding that to `CloseAgreement`.

I'm wondering if we should remove `observationPeriodTime` and `observationPeriodLedgerGap` from the `Channel` in this case? Since now it's relative to the close agreement and for 1 source of truth 🤔 

alternatively naming the fields something different on the close agreement to differentiate

**Comment by leighmcculloch** [comment]
I'd keep the names the same as different names on channel and close agreement may imply there's a different concept and the similar naming is helpful.

If we can remove them on the channel that would be similar to how we have the balance only on the agreement, so that could work, however it would move the observation period fields to the Open rather than the New. I think that is okay.
