### ISSUE TITLE
sdk/state: reject new updates once a coordinated close is in progress or complete

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#133]
Once a coordinated close is in progress or complete it isn't safe to perform payments, because the coordinated close is an immediate close with no delay. We should make the `Channel` so that once the coordinated close is begun that no other operations as possible other than closing.

**Comment by acharb** [comment]
is this the same as: https://github.com/stellar/experimental-payment-channels/issues/107 ?

**Comment by leighmcculloch** [comment]
It is! Thanks.

Duplicate of #107.
