### ISSUE TITLE
cap: write proposal to simplify messages for agreement from 3 to 2

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#165]
I think we can reduce the back and forth between participants in a channel from 3 messages back and forth to 2 messages if we introduce a new signer that binds the closing transaction (C_i) and the declaration transaction (D_i) together so that it is impossible to authorize D_i without also revealing the signatures required to authorize C_i.

A brief version of the proposal is:

Add a new signer that is specified as a 32 byte value and a public key that must sign it. I’ll call the signer the HashSig signer. The signer is a single-use signer like the Hash(x) signer.

For a tx dependent on a HashSig signer to be valid the hash in the signer must be signed by the private key of the public key of the signer.

The HashSig signer can be in CAP-21's extraSigner like any other signer can.

In payment channels where we have two txs D and C, where we want D to only be valid if C is also signed, we define D with:
extraSigner set to a HashSig where the value is the hash of C, and the public key is the other participant, the receiver, signing D and C.

By authorizing D they have to sign C’s hash. If the receiving participant signs D but not C and submits D, the sending participant could see D be submitted, get the signature for C out of D, and submit C.

**Comment by acharb** [comment]
> If the receiving participant signs D but not C and submits D, the sending participant could see D be submitted, get the signature for C out of D, and submit C.

does this require the receiving participant to submit D for the sender to be able to submit C?

**Comment by leighmcculloch** [comment]
> If the receiver doesn't send the message back, this ensures that the sender can close the channel

Exactly! If the sender never sees the signed D_i or C_i, and the receiver submits D_i but not C_i, the sender can extract the signature for C_i out of D_i, attach it to C_i, and submit C_i.
