### ISSUE TITLE
Feature Request: Stock Split Operation

### ISSUE THREAD

**Issue by JFWooten4** [stellar/experimental-payment-channels#206]
### What problem does your feature solve?
Cliffnotes: Stellar is very clearly intended for stock representation, but doesn't yet have a split operations which, while meaningless for stablecoins or cryptos, are a functional **requirement** for securities registrars. 

The full details of this request are on the developer mailing list [here](https://groups.google.com/u/4/g/stellar-dev/c/40u3UiqMXk0), and that post presents various ways to skirt around this limitation which fundamentally lack streamlined operation.

### What would you like to see?
A transaction option for forward splits and one for reverse splits, both of which take one split_ratio parameter. An issuer can execute a split on any nonnative asset to update the account balances of all holders or existing unfilled orders.

### What alternatives are there?
See https://groups.google.com/u/4/g/stellar-dev/c/40u3UiqMXk0. It's pretty nasty

**Comment by JFWooten4** [comment]
Wrong repo. My bad. I'm reposting this in https://github.com/stellar/stellar-protocol/issues

**Comment by leighmcculloch** [comment]
It looks like this issue has moved to https://github.com/stellar/stellar-protocol/issues/1015.
