### ISSUE TITLE
sdk/state: error if proposing or confirming a payment or close if channel open is authorized but not executed

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#235]
In #230 we added the capability to identify when the channel hasn't been authorized to be open, and blocking proposing or confirming any payments until that has occurred. When a channel is authorized to be open the channel hasn't actually opened until the open tx has been submitted to the network and the state of the accounts inspected after that to verify the channel is opened and safe to make payments on.

**Comment by acharb** [comment]
@leighmcculloch this is addressing the same as https://github.com/stellar/experimental-payment-channels/issues/261 correct?

**Comment by leighmcculloch** [comment]
This issue is new logic, error in conditions it currently doesn't error in. I thought #261 was a refactor, use the new state instead of interrogating other variables. So they seem like two different things. Maybe worth doing #261 first though.
