### ISSUE TITLE
sdk/state: add memo field to payments

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#313]
Similar to how Stellar transactions have memos it would be useful if channel payments also had a memo for referencing some identifier outside the channel that the payment is for.

I don't think we need to set a size limit on the memo like the Stellar network has. The value could be a string, byte slice, or an integer. We should probably pick one and run with a single type. String or byte slice are the most flexible.

**Comment by acharb** [comment]
+ adding to this ticket to use that memo to ignore older transactions than one we've already ingested w/in the `ingestTxMetaToUpdateBalances` method

**Comment by leighmcculloch** [comment]
> `+` adding to this ticket to use that memo to ignore older transactions than one we've already ingested w/in the `ingestTxMetaToUpdateBalances` method

Actually, I created this issue for another reason, just for referencing and linking payments to things outside the channel. I don't think this issue will help with the `ingestTxMetaToUpdateBalances`.

**Comment by acharb** [comment]
ah ok, I created this ticket to track here then: https://github.com/stellar/experimental-payment-channels/issues/314

**Comment by leighmcculloch** [comment]
Duplicate of #347, and implemented in #348.
