### ISSUE TITLE
sdk: find best way to structure functions to support the back-and-forth of a payment

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#35]
tracking this effort here.

[this slack](https://stellarfoundation.slack.com/archives/C0166LZF4VC/p1621448846008000) convo is a good starting discussion about this

`ProposePayment/ConfirmPayment` tentatively sounds like a good combo. But exploring it more while writing the underlying method code

**Comment by leighmcculloch** [comment]
I _think_ this has been addressed to some degree in the last two PRs we merged, #56, #52.
