### ISSUE TITLE
examples/benchmarks: one-way payments

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#40]
We need to build a demo that operates over a network to coordinate a payment channel and that demonstrates what sort of naive transactions-per-second could be achieved with the way the protocol is currently designed.

The demo should result in us having some benchmarks and numbers that could be shareable.

It is also expected that in the process of writing this demo we will collect learnings about what could be improved. We are likely to find bottlenecks or inconveniences in the SDK for high-performance applications that we haven't yet discovered in our existing tests and examples. If any of these bottlenecks are roadblocks we may want to look into those issues while working on this demo.

**Comment by shanzzam** [comment]
Assigning to Backlog as there isn't any assigned. We can also make this an Epic as there are multiple tasks working toward this issue as a deliverable.
