### ISSUE TITLE
sdk: design the layers above the state machine.

### ISSUE THREAD

**Issue by shanzzam** [stellar/experimental-payment-channels#43]
Create a draft doc for the layers above the state machine.
These include components [previously discussed](https://docs.google.com/document/d/10EuAvYm7j3IKpSHDEsCJsmG7q7VsALio_b2P8h5skPo/edit#):
Transport
Payments, Withdraw, Add funds
Tx information

**Comment by leighmcculloch** [comment]
When we say design the layers above the state machine, this is what I'm currently thinking, and is approximately what I think we discussed on Thursday.

We're currently working on the two boxes in the bottom left. The state box is responsible for maintaining the state of the channel itself, protecting the channel so it is always in a valid state, and preventing the participant from signing a transaction they shouldn't.

The other things need figuring out and we probably have things we can learn from #44 and #45.

I think what is most unclear is what that big wide box is that makes up the future surface layer of the API, and if that should be an SDK API, or should be a service API.

![Diagram](https://user-images.githubusercontent.com/351529/120870580-2394b000-c54e-11eb-90e5-c409ba142b42.png)
[Diagram source](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1#R3Vjfb5swEP5ronUPrQBD0j3mVzdtq1Ypk7Y%2BOnADTwYjczSwv352MAFCm3VrItL1IfV9PoP9fXfnEyMyj4v3kqbRrQiAjxwrKEZkMXIc27Y99U8jZYVMJgYIJQuMUwOs2C8woGXQnAWQdRxRCI4s7YK%2BSBLwsYNRKcWm6%2FZD8O5bUxpCD1j5lPfRbyzAqEKvPavBPwALo%2FrNtmVmYlo7GyCLaCA2LYgsR2QuhcBqFBdz4Jq8mpdq3c0Ts7uNSUjwOQtuP0pC%2BDIupv4lv%2FTzOOHp5bXZG5b1gSFQ5zemkBiJUCSULxt0JkWeBKCfaimr8fksRKpAW4E%2FAbE0YtIchYIijLmZhYLhd738yvGMed%2BaWhTm0VujNEa1Ub27J89voEzk0ocDh3ZNHFEZAh7ws3cqqfAGEQPKUq2TwCmyh%2B4%2BqImzcOfXSKEGRo2%2FUObdsMo8XxhFvyxbi7R5355rlm2tAQV1hhS0rmhDKTr5LyUlg0pKXl2S2h09G3nPR1H7pWV3u3QqJS1bDqlgCWatJ99pQDmYTsWt723Tpzhk7zb9gz9xrb1wqnbQBNfuKP8eb4bCB8pzQ8Nq8Wmk7%2F0b9ftF%2BhFkKBVLIukFZhN2OgQ2EUNYpXSr2Ea1bt0QM%2B8BiVAcFr6vU9ElsCbIvjb2pmmj3LqNilotVI0dP1udV5etw9Xfutc%2Beba%2BTNJ%2BQiBFGDljrjY9W0s1CvXoItP427PLCmfczwrbeSQr3FNlhdOj8BayjIYsCQdny3XOjS3SY%2BurpEmWqsIwOFve%2BNzYGvfYGrIC2636a12Rvb%2FDBVkZdyCZogXk8Yut98xi6w5Za72emAt4AC5SkG9UY2XNRQA9ebOIpnqYx3zqo1DczXSMM1%2FpR9fA70TGtu0KWawFoohbDlPOQj2BYi9XRI6cJTDfffKxjpNAZNJNIK%2BfP%2BSR9BmfrGHpX2%2FbakP9qsOzZjnjwbZQWxdYrLV1flcccU5XhpTZfECruuzmMyRZ%2FgY%3D)

**Comment by nikhilsaraf** [comment]
Yes, I agree. I think that's something we should take inspiration from the research of other L2 SDKs while combining that with what we think will be an intuitive interface for Stellar.

**Comment by leighmcculloch** [comment]
While working on #122, which is ongoing, it is becoming more evident that an orchestrator will take a load off an application implementing and I want to experiment more with this idea. I plan to pickup this issue next week, take the design doc linked above and iterate on that design in code inside the example application I am working on. I've self-assigned the task to myself for this work.
