### ISSUE TITLE
research: Bitcoin-based L2 SDKs

### ISSUE THREAD

**Issue by shanzzam** [stellar/experimental-payment-channels#44]
@nikhilsaraf commented on [Tue May 25 2021](https://github.com/stellar/voyager/issues/73)

- [x] Bitcoin examples

**Comment by shanzzam** [comment]
@nikhilsaraf please attach a link to your findings here.

**Comment by nikhilsaraf** [comment]
Here's the doc I was using to capture my findings on the Bitcoin Lightning network research. Didn't go as deep as I had wanted to but got a good idea of how the APIs are structured and which we can dig deeper into based on what is similar to our goals:
https://docs.google.com/document/d/1-u5F1rcri3p4O0bmJ7bI9XI2IDmqK3Bpk66H4VpsvOE/edit#

**Comment by nikhilsaraf** [comment]
Here's the doc I was using to capture my findings on the Bitcoin Lightning network research. Didn't go as deep as I had wanted to but got a good idea of how the APIs are structured and which we can dig deeper into based on what is similar to our goals:
https://docs.google.com/document/d/1-u5F1rcri3p4O0bmJ7bI9XI2IDmqK3Bpk66H4VpsvOE/edit#

**Comment by nikhilsaraf** [comment]
Here's the doc I was using to capture my findings on the Bitcoin Lightning network research. Didn't go as deep as I had wanted to but got a good idea of how the APIs are structured and which we can dig deeper into based on what is similar to our goals:
https://docs.google.com/document/d/1-u5F1rcri3p4O0bmJ7bI9XI2IDmqK3Bpk66H4VpsvOE/edit#

**Comment by shanzzam** [comment]
@nikhilsaraf and @leighmcculloch has the doc been reviewed yet? This issue is still marked 'in progress' .
