### ISSUE TITLE
Draw a sequence diagram for the Payment Channel Protocol

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#6]
Notes from https://github.com/stellar/voyager/issues/66

- Diagrams of the main possible scenarios for payment channels flow
- Finite state machine diagram.
-- i.e. flow chart describing your next possible states from your current state. [example](https://en.wikipedia.org/wiki/Finite-state_machine#/media/File:Finite_state_machine_example_with_comments.svg)

**Comment by shanzzam** [comment]
Leaving this open in case more diagrams are needed, as mentioned in #15

**Comment by acharb** [comment]
I think we can close this. I can just create tickets for new diagrams we want as needed w/ descriptions there, like I did for this ticket https://github.com/stellar/experimental-payment-channels/issues/30
