### ISSUE TITLE
sdk/state: distinguish between the not signed and incomplete, or wrong signature / wrong data.

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#65]
Probably need to error on extra/unverifiable signatures.

**Comment by leighmcculloch** [comment]
Let's add a third parameter to the confirm functions, `fullySigned`, that will not be false when the item is not fully signed by all parties. It's a little gross, and we can look for better ways, but this is very verbose and accurate representation about the outputs I think.

We should also still add an error for extra/unverifiable signatures as you mention.

**Comment by leighmcculloch** [comment]
Closed by #76
