### ISSUE TITLE
sdk: draft an api design to abstract the payment channel protocol from apps

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/experimental-payment-channels#8]
What's involved:

- [x] Knowledge gain of what we have to date
- [x] Create draft document to share and review
- [x] Review the sequence diagram from https://github.com/stellar/experimental-payment-channels/issues/6
- [x] Review and adjust draft documentation
- [x] Meet w/ the larger team to discuss the design

Deliverable is a first draft of an SDK we can iterate on for a final draft.

**Comment by nikhilsaraf** [comment]
https://docs.google.com/document/d/10EuAvYm7j3IKpSHDEsCJsmG7q7VsALio_b2P8h5skPo/edit#heading=h.jxh73zhye47c
