### ISSUE TITLE
sdk/state: may need to add locking to account balances when updating

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#84]
probably balances will need locking when they're getting updated. Probably should be addressed when we start demoing with high TPS with networking done

**Comment by leighmcculloch** [comment]
I'm not convinced yet that this should be part of `state.Channel`. I think it is okay for us to say the `state.Channel` object is not thread safe, and then to provide another type, `syncstate.Channel` (or some other name), that wraps a `state.Channel` and makes it thread safe. This keeps the main channel code simpler, and isolates code that will be concerned with concurrency.

Thoughts?
