### ISSUE TITLE
sdk/state: store the "open" object on channel similar to the update and close channel steps do

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#92]
Right now we're storing the "payment" object `latestUnconfirmedPayment`  during the update steps, and the "closing" object `latestCloseAgreement` and `coordinatedClose` on channel. I'm wondering if we should also be storing the "open" object on the channel as well.

1. Keeps that same pattern
2. Right now when User A proposes an open, and signs txC, they're not storing that signature. So technically User B can return that "open" w/o User A's signature. This is the reason we stored payment and close on the channel so we don't lose signatures

I'm thinking we should do the same here. I'm also wondering if there's a nifty trick we could implement since open, update, close all use this same pattern of storing the message before sending and verifying it when the message is returned

wdyt? @nikhilsaraf @leighmcculloch

**Comment by leighmcculloch** [comment]
I think we should do the same.

> I'm also wondering if there's a nifty trick we could implement since open, update, close all use this same pattern

My opinion is we should not try and find a nifty trick to reduce code duplication for this. There isn't enough code here to benefit from that yet, and it'll be simpler to maintain, delete, and evolve this code if we don't.
