### ISSUE TITLE
sdk/state: don't allow a non-native closing agreement to cause an escrow account to exceed its asset limit

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#93]
we should store the channel asset limit either on the "open" object ([this ticket](https://github.com/stellar/experimental-payment-channels/issues/92)). Or possibly store on the channel balance. Once stored then validate new payments against it

blocked by merge of: https://github.com/stellar/experimental-payment-channels/pull/78

**Comment by leighmcculloch** [comment]
I think we should store it on the second option you mention, the channel balance, because it will be possible to change the asset limit over time.

**Comment by leighmcculloch** [comment]
I changed the title of this issue because its less about the channel having an asset limit, but the escrow account that is the destination of the payment and its limit.

**Comment by acharb** [comment]
currently there's an issue that a a user could validate a payment doesn't surpass the escrow account assetLimit, but then the other party sends an amount to the escrow account that maxes out the asset limit. Which would cause the payment to fail.

This would be fixed with the separated disbursement ticket though: https://github.com/stellar/experimental-payment-channels/issues/80

at least, the payment could fail but the channel wont be stuck open (and the malicious actor would only hurt themselves)

**Comment by leighmcculloch** [comment]
I think we can disregard this issue because of #147 and also because of #146.

Please reopen if you disagree.
